name: Tests

on:
    push:
    pull_request:

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Cache
              uses: actions/cache@v3
              id: composer-cache
              with:
                  path: vendor
                  key: ${{ runner.os }}-{{ hashFiles(composer.lock) }}-{{ hashFiles(symfony.lock) }}

            - name: Composer install
              run: composer install --prefer-dist --no-progress

            - name: Run tests
              run: ./vendor/bin/codecept run
    cs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Cache
              uses: actions/cache@v3
              id: composer-cache
              with:
                  path: vendor
                  key: ${{ runner.os }}-{{ hashFiles(composer.lock) }}-{{ hashFiles(symfony.lock) }}

            - name: Composer install
              run: composer install --prefer-dist --no-progress

            - name: Run psalm
              run: ./vendor/bin/psalm
